name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: gtest
      uses: mathiasvr/command-output@v1
      id: gtest
      with:
        run: |
          sudo apt-get update && sudo apt-get install -yq libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
    # build project
    - name: build
      uses: mathiasvr/command-output@v1
      id: buid
      with:
        run: |
          mkdir build
          cd build
          cmake ..
          make all
    # run tests
    - name: run tests
      uses: mathiasvr/command-output@v1
      id: run_tests
      with:
        run: |
          cd build
          make test
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: ${{ steps.tests.outputs.stdout }}         
        SLACK_TITLE: CI Test Suite
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
