name: build and run tests
on:
  push:
    branches: [ main, test_platform.io ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # install dependencies
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -yq libgtest-dev cmake
    # build project
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make all
    # run tests
    - name: run tests
      run: |
        cd build
        make test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
        
      - uses: actions/upload-artifact@v3
        with:
          name: TonUINO_firmware
          path: .pio/build/**/firmware.hex
